=== VidhiPate/xml-js/week-4/index.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE main [
    <!ELEMENT main (main+)>
    <!ELEMENT main (mainName, Sizes, prices)>
    <!ATTLIST main id ID #REQUIRED>
    <!ELEMENT mainName (#PCDATA)>
    <!ELEMENT Sizes (size+)>
    <!ATTLIST size description CDATA #REQUIRED>
    <!ELEMENT size (#PCDATA)>
    <!ELEMENT prices (price+)>
    <!ATTLIST price currency CDATA #REQUIRED>
    <!ELEMENT price (#PCDATA)>
]>

=== VidhiPate/xml-js/week-4/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE main SYSTEM "index.dtd">
<!DOCTYPE main SYSTEM "index.xsd">
<main>
    <main id="a332d8d2-86d7-11ec-a8a3-0242ac120002">
        <mainName>Microfleece hoodie</mainName>
        <Sizes>
            <size description="xs">0 items</size>
            <size description="s">3 items</size>
            <size description="m">13 items</size>
            <size description="l">5 items</size>
            <size description="xl">2 items</size>
        </Sizes>
        <prices>
            <price currency="USD">USD&#36;49.99</price>
            <price currency="CAD">CAD&#36;59.99</price>
        </prices>
    </main>
    <main id="a332dac6-86d7-11ec-a8a3-0242ac120002">
        <mainName>Vintage Soft Hoodie</mainName>
        <Sizes>
            <size description="xs">3 items</size>
            <size description="s">8 items</size>
            <size description="m">25 items</size>
            <size description="l">12 items</size>
            <size description="xl">4 items</size>
        </Sizes>
        <prices>
            <price currency="USD">USD&#36;39.99</price>
            <price currency="CAD">CAD&#36;49.99</price>
        </prices>
    </main>
    <main id="a332dbf2-86d7-11ec-a8a3-0242ac120002">
        <mainName>Crewneck Sweatshirt</mainName>
        <Sizes>
            <size description="xs">0 items</size>
            <size description="s">0 items</size>
            <size description="m">15 items</size>
            <size description="l">13 items</size>
            <size description="xl">0 items</size>
        </Sizes>
        <prices>
            <price currency="CAD">CAD&#36;47.97</price>
        </prices>
    </main>
    <main id="a332dd0a-86d7-11ec-a8a3-0242ac120002">
        <mainName>French Terry Raglan Crewneck Sweatshirt</mainName>
        <Sizes>
            <size description="xs">0 items</size>
            <size description="s">0 items</size>
            <size description="m">0 items</size>
            <size description="l">1 items</size>
            <size description="xl">0 items</size>
        </Sizes>
        <prices>
            <price currency="USD">USD&#36;37.97</price>
        </prices>
    </main>
</main>
